---
base: ../prefetch-dependencies/prefetch-dependencies.yaml
add:
  - use-source
  - create-source
  - create-prefetch
additionalSteps:
  - at: 0
    name: skip-ta
    image: quay.io/konflux-ci/task-runner:3.2.0@sha256:ba5789d2bc04146431e492083c67b86de26d5b17891dc27f67db850a397b66d3
    when:
      - input: $(params.input)
        operator: in
        values: [""]
    env:
      - name: SOURCE_ARTIFACT
        value: $(params.SOURCE_ARTIFACT)
    computeResources:
      limits:
        memory: 64Mi
      requests:
        cpu: 50m
        memory: 64Mi
    script: |
      #!/bin/bash

      echo -n "${SOURCE_ARTIFACT}" > "$(results.SOURCE_ARTIFACT.path)"
      echo -n "" > "$(results.CACHI2_ARTIFACT.path)"
stepWhen:
  use-trusted-artifact:
    - input: $(params.input)
      operator: notin
      values: [""]
  create-trusted-artifact:
    - input: $(params.input)
      operator: notin
      values: [""]
preferStepTemplate: true
removeWorkspaces:
  - source
replacements:
  workspaces.source.path: /var/workdir
useTAVolumeMount: true
